"""#1 migrate to sqlite

Revision ID: 03076247d6f4
Revises: 
Create Date: 2024-09-06 00:26:55.154778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03076247d6f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_users',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('STREAMER', 'GAME', 'UNSELECTED', name='category'), nullable=False),
    sa.Column('set_name', sa.String(length=64), nullable=True),
    sa.Column('get_from', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_users_guild_id'), 'discord_users', ['guild_id'], unique=False)
    op.create_table('twitch_games',
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('game_name')
    )
    op.create_table('twitch_streamers',
    sa.Column('streamer_name', sa.String(), nullable=False),
    sa.Column('streamer_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('streamer_id'),
    sa.UniqueConstraint('streamer_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitch_streamers')
    op.drop_table('twitch_games')
    op.drop_index(op.f('ix_discord_users_guild_id'), table_name='discord_users')
    op.drop_table('discord_users')
    # ### end Alembic commands ###
